### PR TITLE
Just a styling

### PR DESCRIPTION
**Pull request by joker314**
Added some CSS and some links, but not much compared to what I added (not merged yet) to griffpatch.github.io

### CODE REVIEW

**Comment by Sigton** [comment]
I didn't notice your pull request, oops :P

Sigton

**Comment by AwesomeMinecrafter94** [comment]
How do I add stuff to the website?

**Comment by Sigton** [comment]
Sorry, but might as well close this :P

Sigton

**Comment by joker314** [comment]
So you don't want the styling? :P

**Comment by Sigton** [comment]
I kinda styled it myself xD

Sigton

**Pull request closed without merging**
