### PR TITLE
Aesthetics changees

### PR DESCRIPTION
**Pull request by SilversApprentice**
Missed a semicolon

### CODE REVIEW

**Comment by Sigton** [comment]
Since this is kinda out of date I'll think I just close this... (sorry)

Sigton

**Comment by SilversApprentice** [comment]
I'm confused. You haven't updated the site since I've added these updates, so I don't see how it's out of date

**Comment by Sigton** [comment]
I think the problem was you forked it before I changed the site, and then made your changes to an old version.

Sigton

**Comment by SilversApprentice** [comment]
Ah k

**Pull request closed without merging**
